spring.application.name=api
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/projetofinanceiro_api
spring.datasource.username=isadora
spring.datasource.password=123mudar